allowBuilds:
  better-sqlite3: false
  esbuild: true
  lightningcss: true
  msgpackr-extract: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@rolldown/binding-android-arm64@1.2.2'
