/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as mainAuthRouteRouteImport } from './routes/(main)/auth/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as mainAuthSignUpRouteImport } from './routes/(main)/auth/sign-up'
import { Route as mainAuthSignInRouteImport } from './routes/(main)/auth/sign-in'

const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const mainAuthRouteRoute = mainAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => mainRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAuthSignUpRoute = mainAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => mainAuthRouteRoute,
} as any)
const mainAuthSignInRoute = mainAuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => mainAuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof mainAuthRouteRouteWithChildren
  '/': typeof mainIndexRoute
  '/auth/sign-in': typeof mainAuthSignInRoute
  '/auth/sign-up': typeof mainAuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/auth': typeof mainAuthRouteRouteWithChildren
  '/': typeof mainIndexRoute
  '/auth/sign-in': typeof mainAuthSignInRoute
  '/auth/sign-up': typeof mainAuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/(main)/auth': typeof mainAuthRouteRouteWithChildren
  '/(main)/': typeof mainIndexRoute
  '/(main)/auth/sign-in': typeof mainAuthSignInRoute
  '/(main)/auth/sign-up': typeof mainAuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth' | '/' | '/auth/sign-in' | '/auth/sign-up' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/' | '/auth/sign-in' | '/auth/sign-up' | '/api/auth/$'
  id:
    | '__root__'
    | '/(main)'
    | '/(main)/auth'
    | '/(main)/'
    | '/(main)/auth/sign-in'
    | '/(main)/auth/sign-up'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/(main)/auth': {
      id: '/(main)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof mainAuthRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/sign-up': {
      id: '/(main)/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof mainAuthSignUpRouteImport
      parentRoute: typeof mainAuthRouteRoute
    }
    '/(main)/auth/sign-in': {
      id: '/(main)/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof mainAuthSignInRouteImport
      parentRoute: typeof mainAuthRouteRoute
    }
  }
}

interface mainAuthRouteRouteChildren {
  mainAuthSignInRoute: typeof mainAuthSignInRoute
  mainAuthSignUpRoute: typeof mainAuthSignUpRoute
}

const mainAuthRouteRouteChildren: mainAuthRouteRouteChildren = {
  mainAuthSignInRoute: mainAuthSignInRoute,
  mainAuthSignUpRoute: mainAuthSignUpRoute,
}

const mainAuthRouteRouteWithChildren = mainAuthRouteRoute._addFileChildren(
  mainAuthRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainAuthRouteRoute: typeof mainAuthRouteRouteWithChildren
  mainIndexRoute: typeof mainIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainAuthRouteRoute: mainAuthRouteRouteWithChildren,
  mainIndexRoute: mainIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
