/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as mainRouteRouteImport } from './routes/(main)/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as mainIndexRouteImport } from './routes/(main)/index'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as mainAuthRouteRouteImport } from './routes/(main)/auth/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as mainAuthSignUpRouteImport } from './routes/(main)/auth/sign-up'
import { Route as mainAuthSignInRouteImport } from './routes/(main)/auth/sign-in'
import { Route as mainAuthResetPasswordRouteImport } from './routes/(main)/auth/reset-password'
import { Route as mainAuthRequestPasswordResetRouteImport } from './routes/(main)/auth/request-password-reset'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const mainRouteRoute = mainRouteRouteImport.update({
  id: '/(main)',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const mainIndexRoute = mainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => mainRouteRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const mainAuthRouteRoute = mainAuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => mainRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const mainAuthSignUpRoute = mainAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => mainAuthRouteRoute,
} as any)
const mainAuthSignInRoute = mainAuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => mainAuthRouteRoute,
} as any)
const mainAuthResetPasswordRoute = mainAuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => mainAuthRouteRoute,
} as any)
const mainAuthRequestPasswordResetRoute =
  mainAuthRequestPasswordResetRouteImport.update({
    id: '/request-password-reset',
    path: '/request-password-reset',
    getParentRoute: () => mainAuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/auth': typeof mainAuthRouteRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/': typeof mainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/request-password-reset': typeof mainAuthRequestPasswordResetRoute
  '/auth/reset-password': typeof mainAuthResetPasswordRoute
  '/auth/sign-in': typeof mainAuthSignInRoute
  '/auth/sign-up': typeof mainAuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/auth': typeof mainAuthRouteRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/': typeof mainIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/auth/request-password-reset': typeof mainAuthRequestPasswordResetRoute
  '/auth/reset-password': typeof mainAuthResetPasswordRoute
  '/auth/sign-in': typeof mainAuthSignInRoute
  '/auth/sign-up': typeof mainAuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(main)': typeof mainRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/(main)/auth': typeof mainAuthRouteRouteWithChildren
  '/dashboard/profile': typeof DashboardProfileRoute
  '/(main)/': typeof mainIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/(main)/auth/request-password-reset': typeof mainAuthRequestPasswordResetRoute
  '/(main)/auth/reset-password': typeof mainAuthResetPasswordRoute
  '/(main)/auth/sign-in': typeof mainAuthSignInRoute
  '/(main)/auth/sign-up': typeof mainAuthSignUpRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/auth'
    | '/dashboard/profile'
    | '/'
    | '/dashboard/'
    | '/auth/request-password-reset'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/dashboard/profile'
    | '/'
    | '/dashboard'
    | '/auth/request-password-reset'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/(main)'
    | '/dashboard'
    | '/(main)/auth'
    | '/dashboard/profile'
    | '/(main)/'
    | '/dashboard/'
    | '/(main)/auth/request-password-reset'
    | '/(main)/auth/reset-password'
    | '/(main)/auth/sign-in'
    | '/(main)/auth/sign-up'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  mainRouteRoute: typeof mainRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)': {
      id: '/(main)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof mainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(main)/': {
      id: '/(main)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof mainIndexRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(main)/auth': {
      id: '/(main)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof mainAuthRouteRouteImport
      parentRoute: typeof mainRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(main)/auth/sign-up': {
      id: '/(main)/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof mainAuthSignUpRouteImport
      parentRoute: typeof mainAuthRouteRoute
    }
    '/(main)/auth/sign-in': {
      id: '/(main)/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof mainAuthSignInRouteImport
      parentRoute: typeof mainAuthRouteRoute
    }
    '/(main)/auth/reset-password': {
      id: '/(main)/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof mainAuthResetPasswordRouteImport
      parentRoute: typeof mainAuthRouteRoute
    }
    '/(main)/auth/request-password-reset': {
      id: '/(main)/auth/request-password-reset'
      path: '/request-password-reset'
      fullPath: '/auth/request-password-reset'
      preLoaderRoute: typeof mainAuthRequestPasswordResetRouteImport
      parentRoute: typeof mainAuthRouteRoute
    }
  }
}

interface mainAuthRouteRouteChildren {
  mainAuthRequestPasswordResetRoute: typeof mainAuthRequestPasswordResetRoute
  mainAuthResetPasswordRoute: typeof mainAuthResetPasswordRoute
  mainAuthSignInRoute: typeof mainAuthSignInRoute
  mainAuthSignUpRoute: typeof mainAuthSignUpRoute
}

const mainAuthRouteRouteChildren: mainAuthRouteRouteChildren = {
  mainAuthRequestPasswordResetRoute: mainAuthRequestPasswordResetRoute,
  mainAuthResetPasswordRoute: mainAuthResetPasswordRoute,
  mainAuthSignInRoute: mainAuthSignInRoute,
  mainAuthSignUpRoute: mainAuthSignUpRoute,
}

const mainAuthRouteRouteWithChildren = mainAuthRouteRoute._addFileChildren(
  mainAuthRouteRouteChildren,
)

interface mainRouteRouteChildren {
  mainAuthRouteRoute: typeof mainAuthRouteRouteWithChildren
  mainIndexRoute: typeof mainIndexRoute
}

const mainRouteRouteChildren: mainRouteRouteChildren = {
  mainAuthRouteRoute: mainAuthRouteRouteWithChildren,
  mainIndexRoute: mainIndexRoute,
}

const mainRouteRouteWithChildren = mainRouteRoute._addFileChildren(
  mainRouteRouteChildren,
)

interface DashboardRouteRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  mainRouteRoute: mainRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
